server:
  port: 8088

## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/sstore
    username: pilot
    password: pilot

  flyway:
    url: {datasource.url}
    user: {datasource.username}
    password: {datasource.password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

jwt:
  secret: secret
